export const Quizzes = [
    {
        prompt: "What is 1+3?",
        optionA: "24",
        optionB: "5",
        optionC: "4",
        optionD: "2",
        answer: "c",
    },
    {
        prompt: "What is the capital of France?",
        optionA: "Berlin",
        optionB: "Madrid",
        optionC: "Paris",
        optionD: "Rome",
        answer: "c",
    },
    {
        prompt: "What is 7 * 6?",
        optionA: "42",
        optionB: "36",
        optionC: "48",
        optionD: "49",
        answer: "a",
    },
    {
        prompt: "What is the largest planet in our solar system?",
        optionA: "Earth",
        optionB: "Mars",
        optionC: "Jupiter",
        optionD: "Saturn",
        answer: "c",
    },
    {
        prompt: "Which element has the chemical symbol 'O'?",
        optionA: "Oxygen",
        optionB: "Gold",
        optionC: "Silver",
        optionD: "Iron",
        answer: "a",
    },
    {
        prompt: "Who wrote 'Romeo and Juliet'?",
        optionA: "Mark Twain",
        optionB: "William Shakespeare",
        optionC: "Charles Dickens",
        optionD: "J.K. Rowling",
        answer: "b",
    },
    {
        prompt: "What is the square root of 64?",
        optionA: "6",
        optionB: "7",
        optionC: "8",
        optionD: "9",
        answer: "c",
    },
    {
        prompt: "In what year did World War II end?",
        optionA: "1918",
        optionB: "1939",
        optionC: "1945",
        optionD: "1965",
        answer: "c",
    },
    {
        prompt: "What is the powerhouse of the cell?",
        optionA: "Nucleus",
        optionB: "Mitochondria",
        optionC: "Ribosome",
        optionD: "Cell wall",
        answer: "b",
    },
    {
        prompt: "Which country is known as the Land of the Rising Sun?",
        optionA: "China",
        optionB: "Japan",
        optionC: "South Korea",
        optionD: "Vietnam",
        answer: "b",
    },
    {
        prompt: "What is the freezing point of water?",
        optionA: "0°C",
        optionB: "32°C",
        optionC: "100°C",
        optionD: "212°C",
        answer: "a",
    },
    {
        prompt: "Who was the first President of the United States?",
        optionA: "Abraham Lincoln",
        optionB: "George Washington",
        optionC: "John Adams",
        optionD: "Thomas Jefferson",
        answer: "b",
    },
    {
        prompt: "What is the longest river in the world?",
        optionA: "Amazon",
        optionB: "Nile",
        optionC: "Mississippi",
        optionD: "Yangtze",
        answer: "b",
    },
    {
        prompt: "How many sides does a hexagon have?",
        optionA: "5",
        optionB: "6",
        optionC: "7",
        optionD: "8",
        answer: "b",
    },
    {
        prompt: "Who painted the Mona Lisa?",
        optionA: "Vincent van Gogh",
        optionB: "Leonardo da Vinci",
        optionC: "Pablo Picasso",
        optionD: "Claude Monet",
        answer: "b",
    },
    {
        prompt: "What is the chemical formula for water?",
        optionA: "CO2",
        optionB: "O2",
        optionC: "H2O",
        optionD: "NaCl",
        answer: "c",
    },
    {
        prompt: "Which planet is closest to the sun?",
        optionA: "Venus",
        optionB: "Mars",
        optionC: "Mercury",
        optionD: "Earth",
        answer: "c",
    },
    {
        prompt: "What is the capital of Italy?",
        optionA: "Paris",
        optionB: "Rome",
        optionC: "Athens",
        optionD: "Lisbon",
        answer: "b",
    },
    {
        prompt: "What is the speed of light?",
        optionA: "300,000 km/s",
        optionB: "150,000 km/s",
        optionC: "1,000,000 km/s",
        optionD: "100,000 km/s",
        answer: "a",
    },
    {
        prompt: "How many continents are there?",
        optionA: "5",
        optionB: "6",
        optionC: "7",
        optionD: "8",
        answer: "c",
    }
];
